---
collections:
  - name: community.general
  - name: ansible.posix
  - name: https://github.com/RedHatSatellite/satellite-operations-collection.git
    type: git
    version: master
  - name: https://github.com/RedHatSatellite/satellite-ansible-collection.git
    type: git
    version: develop
